name: Deployment

on:
  pull_request:
    branches: [main]
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn install
      - name: Lint code
        run: yarn lint
      - run: echo "${{github.ref_name}} --- ${{github.event_name}}"
      - name: Build project
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: yarn build
      - name: Check build files
        run: ls -l dist
