name: Deployment

on:
  pull_request:
    branches: [main]
  push:
    branches: [main, develop]
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

env:
  artifact_name: build-artifact
  artifact_path: dist

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn install
      - name: Lint code
        run: yarn lint
      # TODO: Add test steps
      - name: Build project
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.artifact_path }}
  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build
    # if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.artifact_path }}
      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          mv dist/index.html dist/200.html
          npx surge --project ${{ env.artifact_path }} --domain ${{ secrets.SURGE_DOMAIN }}
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
